(function initializePaiData(globalScope) {
  "use strict";

  const rawQuestions = [
    [1, "Meus amigos e minhas amigas estão disponíveis quando preciso deles."],
    [2, "Tenho conflitos internos que me causam problemas."],
    [3, "Minhas condições de saúde restringiram minhas atividades."],
    [4, "Fico tão tenso(a) em certas situações que tenho muita dificuldade para lidar com elas."],
    [5, "Tenho que fazer algumas coisas de determinada maneira; caso contrário, fico nervoso(a)."],
    [6, "Quase o tempo todo, fico triste sem nenhuma razão."],
    [7, "Muitas vezes, penso e falo tão rápido que as outras pessoas não conseguem me acompanhar."],
    [8, "Pode-se confiar na maioria das pessoas que conheço."],
    [9, "Às vezes, não me lembro de quem sou."],
    [10, "Tenho algumas ideias que outras pessoas consideram estranhas."],
    [11, "Normalmente, eu me comportava bem na escola."],
    [12, "Durante anos, consultei muitos médicos."],
    [13, "Sou uma pessoa muito sociável."],
    [14, "Meu humor pode mudar muito de repente."],
    [15, "Às vezes, sinto culpa pela quantidade de álcool que bebo."],
    [16, "Sou uma pessoa que enfrenta a vida."],
    [17, "Minha opinião sobre mim mesmo(a) muda muito."],
    [18, "As pessoas ficariam surpresas se eu gritasse com alguém."],
    [19, "Meus relacionamentos têm sido conturbados."],
    [20, "Às vezes, gostaria de estar morto(a)."],
    [21, "As pessoas têm medo do meu temperamento."],
    [22, "Às vezes, uso drogas para me sentir melhor."],
    [23, "Já experimentei quase todos os tipos de drogas."],
    [24, "Às vezes, dou importância excessiva a pequenas coisas que me incomodam."],
    [25, "Frequentemente, tenho dificuldade para me concentrar porque fico nervoso(a)."],
    [26, "Muitas vezes, tenho medo de me atrapalhar e dizer algo inadequado."],
    [27, "Acho que decepcionei todo mundo."],
    [28, "Tenho muitas ideias brilhantes."],
    [29, "Algumas pessoas se esforçam para me incomodar."],
    [30, "Parece que não me relaciono muito bem com as pessoas."],
    [31, "Já pedi dinheiro emprestado sabendo que não iria devolver."],
    [32, "Quase o tempo todo, sinto-me bem."],
    [33, "Frequentemente, sinto medo."],
    [34, "Continuo revivendo algo terrível que me aconteceu."],
    [35, "Quase o tempo todo, não me sinto bem."],
    [36, "Posso ser muito exigente quando quero que as coisas sejam feitas rapidamente."],
    [37, "Geralmente, as pessoas me tratam de maneira justa."],
    [38, "Minha cabeça fica confusa."],
    [39, "Fico fascinado(a) por fazer coisas perigosas."],
    [40, "Gosto muito de filmes violentos."],
    [41, "Gosto de estar junto da minha família."],
    [42, "Preciso fazer algumas mudanças importantes na minha vida."],
    [43, "Já tive doenças que os médicos não conseguiram explicar."],
    [44, "Não consigo fazer algumas coisas bem por causa do nervosismo."],
    [45, "Tenho impulsos fortes e luto para controlá-los."],
    [46, "Esqueci como é sentir-se contente."],
    [47, "Assumo tantas responsabilidades que não consigo dar conta delas."],
    [48, "Preciso estar atento(a) à possibilidade de as pessoas serem desleais comigo."],
    [49, "Tenho visões nas quais me vejo forçado(a) a cometer crimes."],
    [50, "Às vezes, outras pessoas colocam ideias na minha cabeça."],
    [51, "Já causei, de propósito, danos à propriedade de outra pessoa."],
    [52, "Meus problemas de saúde são muito complicados."],
    [53, "Acho fácil fazer novas amizades."],
    [54, "Meus estados de humor se tornam muito intensos."],
    [55, "Tenho dificuldade para controlar o consumo de álcool."],
    [56, "Sou um(a) líder nato(a)."],
    [57, "Às vezes, sinto-me terrivelmente vazio(a) por dentro."],
    [58, "Digo tudo o que penso às pessoas quando considero que elas merecem ouvir."],
    [59, "Quero que certas pessoas saibam o quanto me magoaram."],
    [60, "Já pensei em maneiras de me matar."],
    [61, "Às vezes, fico com tanta raiva que perco completamente o controle."],
    [62, "As pessoas já me disseram que tenho problemas com drogas."],
    [63, "Nunca uso drogas para conseguir avançar na vida."],
    [64, "Às vezes, evito encontrar alguém que não gosta de mim."],
    [65, "Frequentemente, é difícil me divertir porque fico preocupado(a) com as coisas."],
    [66, "Tenho medos exagerados."],
    [67, "Às vezes, sinto que não tenho valor."],
    [68, "Tenho talentos especiais que poucas pessoas possuem."],
    [69, "Algumas pessoas fazem coisas para me prejudicar."],
    [70, "Não tenho muito o que dizer a ninguém."],
    [71, "Aproveito-me das outras pessoas quando elas me dão oportunidade."],
    [72, "Sinto muitas dores."],
    [73, "Preocupo-me tanto que, às vezes, sinto que vou desmaiar."],
    [74, "Pensamentos sobre meu passado frequentemente me incomodam quando estou pensando em outra coisa."],
    [75, "Não tenho problemas para dormir."],
    [76, "Fico muito irritado(a) quando as pessoas tentam impedir que eu alcance meus objetivos."],
    [77, "Parece que tenho tanta sorte na vida quanto as outras pessoas."],
    [78, "Às vezes, minhas ideias me confundem."],
    [79, "Faço muitas coisas descontroladas pelo simples prazer de fazê-las."],
    [80, "Às vezes, recebo anúncios pelo correio ou por e-mail que eu não queria receber."],
    [81, "Se eu tiver problemas, tenho com quem conversar."],
    [82, "Preciso mudar algumas coisas em mim, embora isso seja doloroso."],
    [83, "Não consigo explicar por que já perdi a sensibilidade em partes do meu corpo."],
    [84, "Às vezes, sinto medo sem nenhuma razão."],
    [85, "Fico irritado(a) quando as coisas estão fora do lugar."],
    [86, "Tudo parece exigir um grande esforço."],
    [87, "Recentemente, percebi que tenho muito mais energia do que o habitual."],
    [88, "A maioria das pessoas tem boas intenções."],
    [89, "Desde que nasci, parecia que eu estava destinado(a) a ser infeliz."],
    [90, "Às vezes, parece que meus pensamentos são anunciados para que outras pessoas possam ouvi-los."],
    [91, "Já fiz algumas coisas que não eram totalmente legais."],
    [92, "É difícil realizar minhas atividades por causa dos meus problemas médicos."],
    [93, "Gosto de conhecer pessoas novas."],
    [94, "Meu temperamento é muito estável."],
    [95, "Houve momentos em que precisei limitar meu consumo de álcool."],
    [96, "Eu me sairia bem em um trabalho no qual tivesse que dizer aos outros o que fazer."],
    [97, "Preocupa-me muito a possibilidade de outras pessoas me abandonarem."],
    [98, "Quando fico com raiva de pessoas desconhecidas na rua, faço com que elas saibam."],
    [99, "Algumas pessoas que antes eram boas amigas acabaram se voltando contra mim."],
    [100, "Já planejei como me matar."],
    [101, "Às vezes, sou muito violento(a)."],
    [102, "O uso de drogas já me causou problemas financeiros."],
    [103, "Nunca tive problemas no trabalho por causa de drogas."],
    [104, "Às vezes, reclamo demais."],
    [105, "Frequentemente, fico tão preocupado(a) e nervoso(a) que mal consigo suportar."],
    [106, "Fico muito nervoso(a) quando preciso fazer algo diante de outras pessoas."],
    [107, "Não sinto vontade de fazer mais esforços."],
    [108, "Meus planos me tornarão famoso(a) algum dia."],
    [109, "As pessoas ao meu redor são leais a mim."],
    [110, "Sou uma pessoa solitária."],
    [111, "Estou disposto(a) a fazer quase qualquer coisa se considerar que vale a pena."],
    [112, "Tenho boa saúde."],
    [113, "Às vezes, sinto tontura quando estou sob muita pressão."],
    [114, "Há muito tempo, sou incomodado(a) pelas lembranças de uma experiência ruim."],
    [115, "É raro eu ter problemas para dormir."],
    [116, "Às vezes, fico com raiva porque os outros não entendem meus planos."],
    [117, "Já dei muito aos outros, mas recebi pouco em troca."],
    [118, "Às vezes, tenho dificuldade para distinguir ideias diferentes."],
    [119, "Meu comportamento, às vezes, é agitado e barulhento."],
    [120, "Minha modalidade esportiva favorita é o salto em altura."],
    [121, "Passo quase todo o tempo sozinho(a)."],
    [122, "Preciso de ajuda para enfrentar problemas importantes."],
    [123, "Já tive episódios de visão dupla ou visão embaçada."],
    [124, "Não sou o tipo de pessoa que se assusta facilmente."],
    [125, "Consigo relaxar mesmo quando minha casa está desorganizada."],
    [126, "Nada parece me dar muito prazer."],
    [127, "Às vezes, minhas ideias se movem rapidamente."],
    [128, "Normalmente, suponho que as pessoas dizem a verdade."],
    [129, "Acho que tenho três ou quatro personalidades completamente diferentes dentro de mim."],
    [130, "Outras pessoas podem ler meus pensamentos."],
    [131, "Eu costumava contar muitas mentiras para sair de situações difíceis."],
    [132, "Meus problemas médicos parecem sempre difíceis de resolver."],
    [133, "Sou uma pessoa calorosa."],
    [134, "Não controlo muito bem meu humor."],
    [135, "O consumo de álcool parece causar problemas nos meus relacionamentos."],
    [136, "É difícil para mim defender meus interesses."],
    [137, "Frequentemente, pergunto-me o que devo fazer com minha vida."],
    [138, "Não tenho receio de gritar com alguém para que me entenda."],
    [139, "É raro eu me sentir sozinho(a)."],
    [140, "Recentemente, tenho pensado em suicídio."],
    [141, "Às vezes, quebro coisas quando estou com raiva."],
    [142, "Nunca uso drogas ilegais."],
    [143, "Às vezes, ajo de forma tão impulsiva que me meto em problemas."],
    [144, "Às vezes, sou impaciente demais."],
    [145, "Meus amigos e minhas amigas dizem que me preocupo muito."],
    [146, "Não me assusto facilmente."],
    [147, "Parece que não consigo me concentrar muito bem."],
    [148, "Já fiz algumas coisas extraordinárias."],
    [149, "Algumas pessoas tentam impedir meu progresso."],
    [150, "Não tenho um relacionamento próximo com ninguém."],
    [151, "Consigo sair de qualquer situação difícil por meio da conversa."],
    [152, "Quase nunca reclamo de como me sinto fisicamente."],
    [153, "Frequentemente, sinto meu coração bater forte."],
    [154, "Parece que não consigo esquecer algo do passado."],
    [155, "Estou me movimentando mais devagar do que o habitual."],
    [156, "Tenho grandes planos e fico irritado(a) quando as pessoas tentam interferir neles."],
    [157, "As pessoas não valorizam o que fiz por elas."],
    [158, "Às vezes, parece que alguém está bloqueando meus pensamentos."],
    [159, "Quando me canso de um lugar, simplesmente vou embora."],
    [160, "A maioria das pessoas prefere ganhar a perder."],
    [161, "A maioria das minhas amizades me apoia."],
    [162, "Tenho curiosidade sobre por que me comporto da maneira como me comporto."],
    [163, "Houve momentos em que minha visão piorou e depois voltou a melhorar."],
    [164, "Sou uma pessoa muito calma e relaxada."],
    [165, "As pessoas dizem que sou perfeccionista."],
    [166, "Perdi o interesse por coisas de que antes gostava."],
    [167, "Meus amigos e minhas amigas não conseguem acompanhar meu ritmo nas atividades sociais."],
    [168, "As pessoas geralmente escondem suas verdadeiras intenções."],
    [169, "As pessoas não entendem o quanto eu sofro."],
    [170, "Já ouvi vozes que ninguém mais conseguia ouvir."],
    [171, "Gosto de descobrir até onde posso ir sem sofrer consequências."],
    [172, "Tive apenas os problemas de saúde que a maioria das pessoas tem."],
    [173, "Demoro um pouco para me aproximar das pessoas."],
    [174, "Sempre fui uma pessoa bastante feliz."],
    [175, "O álcool me ajuda a lidar com situações sociais."],
    [176, "Sinto-me melhor em situações nas quais sou o(a) líder."],
    [177, "Tenho muita dificuldade para lidar com a separação das pessoas próximas a mim."],
    [178, "Sempre que posso, evito discussões."],
    [179, "Cometi erros importantes ao escolher minhas amizades."],
    [180, "Tenho pensado em suicídio há muito tempo."],
    [181, "Já ameacei machucar outras pessoas."],
    [182, "Já usei medicamentos prescritos para ficar eufórico(a)."],
    [183, "Quando estou aborrecido(a), normalmente faço algo para me machucar."],
    [184, "Não aceito bem críticas."],
    [185, "Não me preocupo com as coisas mais do que a maioria das pessoas."],
    [186, "Não me incomoda dirigir em rodovias."],
    [187, "Não importa o que eu faça, nada dá certo."],
    [188, "Acho que sei a solução para alguns problemas muito importantes."],
    [189, "Há pessoas que querem me fazer mal."],
    [190, "Gosto da companhia de outras pessoas."],
    [191, "Não gosto de ficar preso(a) a outra pessoa."],
    [192, "Tenho dores nas costas."],
    [193, "É fácil para mim relaxar."],
    [194, "Tive experiências terríveis que me fazem sentir culpa."],
    [195, "Frequentemente, acordo cedo e não consigo voltar a dormir."],
    [196, "Fico incomodado(a) quando as pessoas demoram muito para entender minhas ideias."],
    [197, "Normalmente, recebo reconhecimento por tudo o que faço."],
    [198, "Meus pensamentos tendem a mudar rapidamente de uma coisa para outra."],
    [199, "A ideia de criar raízes em um lugar nunca me atraiu."],
    [200, "Meus passatempos favoritos são tiro com arco e colecionar selos."],
    [201, "As pessoas que conheço têm carinho por mim."],
    [202, "Sinto-me confortável comigo mesmo(a), exatamente como sou."],
    [203, "Já tive episódios em que perdi a sensibilidade nas mãos."],
    [204, "Frequentemente, sinto que algo terrível está prestes a acontecer."],
    [205, "Normalmente, fico atento(a) a objetos que podem conter muitos germes."],
    [206, "Não tenho nenhum interesse pela vida."],
    [207, "Sinto que preciso me manter ativo(a) e não descansar."],
    [208, "As pessoas acham que sou muito desconfiado(a)."],
    [209, "De vez em quando, perco completamente a memória."],
    [210, "Há pessoas que tentam controlar meus pensamentos."],
    [211, "Nunca fui expulso(a) nem suspenso(a) da escola quando era jovem."],
    [212, "Já tive algumas doenças incomuns."],
    [213, "As pessoas levam tempo para me conhecer bem."],
    [214, "Houve momentos em que fiquei tão irritado(a) que não consegui expressar toda a minha raiva."],
    [215, "Algumas pessoas ao meu redor acham que bebo álcool demais."],
    [216, "Prefiro deixar que outras pessoas tomem as decisões."],
    [217, "Não fico entediado(a) facilmente."],
    [218, "Não gosto de levantar a voz."],
    [219, "Quando alguém se torna meu amigo ou minha amiga, geralmente continuamos amigos."],
    [220, "A morte seria um alívio."],
    [221, "Na vida adulta, nunca comecei uma briga física."],
    [222, "Não consigo controlar meu uso de drogas."],
    [223, "Sou impulsivo(a) demais para meu próprio bem."],
    [224, "Às vezes, deixo as coisas para a última hora."],
    [225, "Não me preocupo com coisas que não posso controlar."],
    [226, "Não tenho medo de altura."],
    [227, "Acho que coisas boas acontecerão comigo no futuro."],
    [228, "Acho que eu seria um(a) bom(boa) humorista."],
    [229, "As pessoas quase nunca me tratam mal de propósito."],
    [230, "Sempre que posso, gosto de estar junto de outras pessoas."],
    [231, "Não gosto de permanecer por muito tempo em um relacionamento amoroso."],
    [232, "Tenho o estômago sensível."],
    [233, "Quando estou sob muita pressão, às vezes tenho dificuldade para respirar."],
    [234, "Continuo tendo pesadelos sobre meu passado."],
    [235, "Tenho bom apetite."],
    [236, "Não tenho paciência com pessoas que tentam impedir meu progresso."],
    [237, "As pessoas bem-sucedidas geralmente conquistaram seu sucesso."],
    [238, "Às vezes, pergunto-me se estão roubando meus pensamentos."],
    [239, "Gosto de dirigir em alta velocidade."],
    [240, "Não gosto de comprar coisas com preço excessivo."],
    [241, "Na minha família, discutimos mais do que conversamos."],
    [242, "Muitos dos meus problemas são causados por mim mesmo(a)."],
    [243, "Já houve momentos em que minhas pernas ficaram tão fracas que não consegui caminhar."],
    [244, "Quase nunca me sinto ansioso(a) ou tenso(a)."],
    [245, "As pessoas me veem como alguém que presta muita atenção aos pequenos detalhes."],
    [246, "Ultimamente, tenho me sentido contente quase todo o tempo."],
    [247, "Recentemente, precisei de menos sono do que o habitual."],
    [248, "As coisas quase nunca são como parecem por fora."],
    [249, "Às vezes, vejo tudo em preto e branco, sem meio-termo."],
    [250, "Tenho um sexto sentido que me diz o que vai acontecer."],
    [251, "Nunca tive problemas com a justiça."],
    [252, "Para minha idade, tenho uma saúde bastante boa."],
    [253, "Tento incluir pessoas que parecem estar isoladas."],
    [254, "Às vezes, a primeira coisa que faço pela manhã é tomar uma bebida alcoólica."],
    [255, "O consumo de álcool já me causou problemas em casa."],
    [256, "Digo o que tenho em mente."],
    [257, "Normalmente, faço o que outras pessoas me dizem para fazer."],
    [258, "Tenho mau temperamento."],
    [259, "Suporto muita coisa antes de me irritar."],
    [260, "Já pensei no que escreveria em uma nota de suicídio."],
    [261, "Não encontro nenhuma razão para continuar vivendo."],
    [262, "Já tive problemas de saúde por usar drogas."],
    [263, "Gasto dinheiro demais com facilidade."],
    [264, "Às vezes, faço promessas que não consigo cumprir."],
    [265, "Normalmente, preocupo-me mais com as coisas do que deveria."],
    [266, "Não viajo de avião."],
    [267, "Posso contribuir com algo de valor."],
    [268, "Recentemente, tenho me sentido tão confiante que acho que posso realizar qualquer coisa."],
    [269, "As pessoas já juraram contra mim."],
    [270, "Faço amizades com facilidade."],
    [271, "Preocupo-me primeiro comigo; os outros devem cuidar de si mesmos."],
    [272, "Tenho mais dores de cabeça do que a maioria das pessoas."],
    [273, "Minhas mãos suam com frequência."],
    [274, "Desde que tive uma experiência ruim, perdi o interesse pelas coisas de que antes gostava."],
    [275, "Frequentemente, acordo no meio da noite."],
    [276, "Às vezes, fico muito ressentido(a) e me irrito com facilidade."],
    [277, "Não sou o tipo de pessoa que guarda ressentimentos."],
    [278, "Às vezes, as ideias desaparecem de repente da minha cabeça."],
    [279, "Não sou uma pessoa que evita situações arriscadas."],
    [280, "A maioria das pessoas aguarda com satisfação uma consulta ao dentista."],
    [281, "Dedico pouco tempo à minha família."],
    [282, "Consigo resolver meus problemas por conta própria."],
    [283, "Às vezes, algumas partes do meu corpo ficaram paralisadas."],
    [284, "Assusto-me facilmente."],
    [285, "Mantenho controle absoluto sobre mim."],
    [286, "Quase sempre, sou uma pessoa feliz e positiva."],
    [287, "Quase nunca compro coisas por impulso."],
    [288, "As pessoas precisam conquistar minha confiança."],
    [289, "Não tenho nenhuma lembrança boa da minha infância."],
    [290, "Não acredito que existam pessoas capazes de ler a mente."],
    [291, "Nunca peguei nem me apropriei de coisas que não eram minhas."],
    [292, "Gosto de conversar com as pessoas sobre os problemas médicos delas."],
    [293, "Sou uma pessoa afetuosa."],
    [294, "Nunca dirigiria depois de consumir álcool."],
    [295, "Quase nunca bebo álcool."],
    [296, "As pessoas ouvem minhas opiniões."],
    [297, "Quando recebo atendimento ruim em um estabelecimento, falo com o gerente ou responsável."],
    [298, "Meu temperamento nunca me causa problemas."],
    [299, "Minha raiva nunca foge do controle."],
    [300, "Já pensei em como outras pessoas reagiriam se eu me matasse."],
    [301, "Tenho muitos motivos para continuar vivendo."],
    [302, "Meus melhores amigos e minhas melhores amigas são aqueles com quem uso drogas."],
    [303, "Sou uma pessoa desenfreada."],
    [304, "Houve momentos em que eu poderia ter sido mais atencioso(a) do que fui."],
    [305, "Às vezes, fico tão nervoso(a) que tenho medo de morrer."],
    [306, "Não me incomoda viajar de ônibus ou de trem."],
    [307, "Tenho muito sucesso no que faço."],
    [308, "Nunca conseguiria me imaginar famoso(a)."],
    [309, "Sou vítima de uma conspiração."],
    [310, "Mantenho contato com meus amigos e minhas amigas."],
    [311, "Quando faço uma promessa, não considero que sou realmente obrigado(a) a cumpri-la."],
    [312, "Frequentemente, tenho diarreia."],
    [313, "Minhas mãos nunca tremem."],
    [314, "Evito certas coisas que me trazem lembranças ruins."],
    [315, "Tenho pouco interesse por sexo."],
    [316, "Tenho pouca paciência com quem discorda dos meus planos."],
    [317, "Ser útil aos outros traz vantagens no final."],
    [318, "Atualmente, consigo me concentrar tão bem quanto antes."],
    [319, "Nunca me arrisco quando posso evitar."],
    [320, "No meu tempo livre, gosto de ler, assistir à televisão ou simplesmente relaxar."],
    [321, "Tenho muitos problemas financeiros."],
    [322, "Minha vida é imprevisível."],
    [323, "Houve muitas mudanças na minha vida recentemente."],
    [324, "Não há muita estabilidade em casa."],
    [325, "As coisas não vão bem na minha família."],
    [326, "Estou satisfeito(a) com minha situação profissional."],
    [327, "Preocupa-me a possibilidade de não ter dinheiro suficiente para viver."],
    [328, "Meu relacionamento com meu cônjuge, companheiro(a) ou pessoa mais íntima não vai bem."],
    [329, "Tenho problemas psicológicos graves que começaram de repente."],
    [330, "Sou o tipo de pessoa que sente compaixão pelos outros."],
    [331, "Os relacionamentos amorosos são importantes para mim."],
    [332, "Sou muito impaciente com as pessoas."],
    [333, "Tenho mais amigos e amigas do que a maioria das pessoas que conheço."],
    [334, "O consumo de álcool nunca me trouxe problemas."],
    [335, "O consumo de álcool já me causou problemas no trabalho."],
    [336, "Não gosto de dizer às pessoas quando discordo delas."],
    [337, "Sou uma pessoa muito independente."],
    [338, "Quando fico com raiva, tenho muita dificuldade para me acalmar."],
    [339, "As pessoas acham que sou agressivo(a)."],
    [340, "Estou pensando em me suicidar."],
    [341, "As coisas nunca estiveram tão ruins a ponto de eu pensar em suicídio."],
    [342, "Meu uso de drogas nunca causou problemas com minha família ou minhas amizades."],
    [343, "Tenho cuidado ao gastar dinheiro."],
    [344, "É raro eu ficar de mau humor."]
  ];

  const questions = rawQuestions.map(([number, text], index) => {
    if (number !== index + 1) {
      throw new Error("Sequência inválida no item " + number + ".");
    }

    return {
      id: "item_" + number,
      number,
      text
    };
  });

  const data = {
    formCode: "PAI_V2",
    formName: "PAI - Inventário de Avaliação da Personalidade",
    title: "Inventário de Avaliação da Personalidade",
    shortTitle: "PAI",
    prompt: "Leia cada afirmação e indique até que ponto ela é verdadeira para você.",
    questions,
    responses: [
      { value: "totalmente_falso", label: "Totalmente falso", score: 0 },
      { value: "um_pouco_verdadeiro", label: "Um pouco verdadeiro", score: 1 },
      { value: "principalmente_verdadeiro", label: "Principalmente verdadeiro", score: 2 },
      { value: "muito_verdadeiro", label: "Muito verdadeiro", score: 3 }
    ],
    itemsPerPage: 20
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = data;
  }

  if (globalScope) {
    globalScope.PAIData = data;
  }
})(typeof window !== "undefined" ? window : globalThis);
