(function initializeIdcp2Data(globalScope) {
  "use strict";

  const rawQuestions = [
    [1, "É comum que eu permita que outros tomem decisões importantes por mim."],
    [2, "Sempre gosto de estar seguro de ter terminado meu trabalho antes de descansar."],
    [3, "As pessoas me veem como “pão duro”, mas na verdade sou mais prevenido que a maioria."],
    [4, "Não me arrependo das coisas que faço, mesmo que alguém saia prejudicado."],
    [5, "Sinto certo desconforto quando os outros não me ajudam a tomar as decisões."],
    [6, "Tenho pouca vontade de estar com outras pessoas."],
    [7, "Sinto-me diferente e esquisito em relação às outras pessoas."],
    [8, "Frequentemente tenho experiências difíceis de explicar (como premonição, telepatia, sexto sentido, etc.)."],
    [9, "Prefiro não praticar atividades com outras pessoas, pois elas vão me criticar."],
    [10, "Gosto muito de assistir filmes violentos."],
    [11, "Tudo deve estar sempre organizado e em ordem."],
    [12, "As tarefas devem ser sempre realizadas com perfeição."],
    [13, "É difícil pedir ajuda para os outros em um trabalho, porque eles não são tão cuidadosos quanto eu."],
    [14, "As pessoas invejam minhas habilidades."],
    [15, "Ainda não tenho todo o reconhecimento que mereço."],
    [16, "Já pensei em me suicidar."],
    [17, "Não me importo se tiver que bater em alguém."],
    [18, "Costumo fazer coisas que não gosto para ajudar os outros."],
    [19, "As pessoas podem me fazer mudar de ideia facilmente, mesmo quando eu pensava estar decidido."],
    [20, "Quase sempre tenho vontade de estar sozinho e me sinto muito bem assim."],
    [21, "As pessoas pensam que eu, algumas vezes, falo de coisas estranhas e diferentes."],
    [22, "Muitas vezes percebo que as pessoas estão rindo ou caçoando de mim pelas costas."],
    [23, "Às vezes falo coisas, que irritam as pessoas, das quais depois sinto culpa."],
    [24, "As pessoas não me compreendem e não dão o valor que mereço."],
    [25, "Fico extremamente irritado quando recebo ordem dos outros."],
    [26, "Normalmente as pessoas não são confiáveis."],
    [27, "Preciso tomar muito cuidado para não ser enganado pelos meus colegas."],
    [28, "Os outros sempre tentam me prejudicar, explorar ou enganar, mas estou sempre alerta."],
    [29, "Acho necessário estabelecer regras rígidas aos membros da minha família."],
    [30, "Gosto de intimidar e dominar os outros."],
    [31, "Gosto de trabalhar sozinho, pois é difícil achar alguém que faça as coisas do jeito que eu gostaria."],
    [32, "Frequentemente não recebo o tratamento a altura que mereço."],
    [33, "Às vezes faço coisas por impulso sem pensar nas consequências (como sexo, correr com o carro, beber, usar drogas, ou outros)."],
    [34, "Meu humor muda, de um extremo para outro, com muita facilidade."],
    [35, "Costumo fazer coisas para agradar os outros, mesmo que não goste de fazê-las."],
    [36, "Sempre fui muito preocupado com tudo."],
    [37, "Prefiro fazer as coisas sozinho."],
    [38, "Sei que as pessoas ficam me observando."],
    [39, "Frequentemente testemunho experiências sobrenaturais."],
    [40, "Consigo seduzir as pessoas com facilidade."],
    [41, "Muitas vezes faço sacrifícios para ajudar os outros, mesmo que não me peçam."],
    [42, "Às vezes sou explosivo e depois me sinto culpado."],
    [43, "Devemos estar atentos para as verdadeiras intenções dos outros."],
    [44, "Às vezes preciso usar da força para ensinar as pessoas o que elas devem fazer."],
    [45, "Evito ao máximo usar meu dinheiro, prefiro guardá-lo para emergências futuras."],
    [46, "Eu sou assim, em alguns momentos amo aquela pessoa, em outros odeio."],
    [47, "Às vezes fico com raiva, e não consigo me controlar."],
    [48, "Quando as coisas andam mal tendo a perder a noção de mim mesmo."],
    [49, "Já me envolvi em brigas com agressão física."],
    [50, "Tenho medo de ser abandonado e ter que me virar sozinho."],
    [51, "Sei que as pessoas, às vezes, acham que faço coisas estranhas."],
    [52, "As pessoas costumam dizer que sou esquisito."],
    [53, "Interesso-me pouco em fazer amizades."],
    [54, "Prefiro lidar com situações e pessoas conhecidas do que correr riscos."],
    [55, "Em pouco tempo consigo conhecer muito sobre as pessoas a ponto de nos tornarmos amigos."],
    [56, "Consigo rapidamente fazer amizades íntimas."],
    [57, "Ajudo tanto os outros que acabo me prejudicando."],
    [58, "Irrita-me receber ordens."],
    [59, "É muito difícil encontrar amigos confiáveis."],
    [60, "Tenho habilidade de usar o medo para fazer as pessoas realizarem o que quero."],
    [61, "Tendo a ficar violento quando minhas vontades não são satisfeitas."],
    [62, "Sempre resolvo as coisas da mesma maneira, mesmo que isso me traga algum prejuízo."],
    [63, "Sinto-me mal com mudanças nas minhas atividades cotidianas."],
    [64, "Tenho muita dificuldade para fazer as coisas de um modo diferente ao qual já estou familiarizado."],
    [65, "Nunca entrego uma tarefa sem verificar diversas vezes para garantir que está perfeita."],
    [66, "Algo que não está perfeito não vale nada."],
    [67, "Frequentemente não vou a eventos, pois preciso finalizar algo que está quase perfeito."],
    [68, "As pessoas não costumam reparar nos pequenos detalhes, mas eu me prendo muito a eles."],
    [69, "É importante para minha vida que eu me preocupe com os mínimos detalhes."],
    [70, "A maior parte do tempo estou pensando em coisas do trabalho."],
    [71, "Nenhum relacionamento é mais importante que meu trabalho."],
    [72, "O senso de humor das pessoas muitas vezes atrapalha o desempenho no trabalho."],
    [73, "Acredito que é importante ser uma pessoa muito rigorosa."],
    [74, "Penso muito sobre minhas ideias e pouquíssimo sobre as ideias e sentimentos dos outros."],
    [75, "Sou uma pessoa extremamente reservada e evito compartilhar meus sentimentos."],
    [76, "As pessoas me consideram extremamente sério e formal."],
    [77, "A maioria das pessoas me considera muito intelectualizado."],
    [78, "Não há nada melhor do que ter a atenção das pessoas."],
    [79, "É insuportável não ter atenção das pessoas."],
    [80, "Sei como usar as palavras para conseguir o que quero das pessoas."],
    [81, "Eu utilizo meu charme quando quero que as coisas saiam do meu jeito."],
    [82, "Sei que minhas emoções são mais intensas do que da maioria das pessoas."],
    [83, "Minhas emoções são sempre muito extremas."],
    [84, "Minhas emoções estão sempre mudando."],
    [85, "Fico íntimo das pessoas com muita facilidade."],
    [86, "Preciso que as pessoas me digam o que pensam sobre mim."],
    [87, "Sempre estou tentando saber o que as pessoas acham de mim."],
    [88, "Na maior parte do tempo me sinto muito triste."],
    [89, "Muitas vezes eu sinto que a minha vida não tem sentido algum."],
    [90, "A vida das pessoas que conheço é muito mais interessante que a minha."],
    [91, "Tento atingir o que as pessoas esperam de mim."],
    [92, "Nos meus relacionamentos meu parceiro parece estar sempre acima de mim."],
    [93, "As pessoas dizem que sou submisso."],
    [94, "É inevitável que algumas pessoas tirem proveito de mim às vezes."],
    [95, "Faço de tudo em meus relacionamentos para servir o outro."],
    [96, "Frequentemente eu deixo meus desejos de lado para satisfazer meu parceiro."],
    [97, "As pessoas parecem ter mais prazer na vida do que eu."],
    [98, "Tudo que eu planejo parece não dar certo."],
    [99, "Não sei fazer nada tão bem quanto os outros."],
    [100, "As coisas boas duram pouco tempo por minha culpa."],
    [101, "Eu geralmente fracasso com as pessoas."],
    [102, "Sinto-me muito mal quando não tenho alguém com quem posso contar."],
    [103, "É insuportável para mim não estar me relacionando com alguém."],
    [104, "Sei que se eu magoar alguém, essa pessoa pode me abandonar."],
    [105, "É horrível ser rejeitado por alguém."],
    [106, "Para não ficar sozinho, qualquer esforço vale a pena."],
    [107, "Quase nunca estou satisfeito comigo."],
    [108, "Sei que faço muitas coisas erradas, e me sinto culpado por isso."],
    [109, "As pessoas fazem as coisas muito melhor que eu."],
    [110, "As pessoas geralmente entendem muito mais das coisas do que eu."],
    [111, "Sei que estou bem abaixo das expectativas e do que deveria ser."],
    [112, "É difícil para mim fazer algo sem ter a opinião dos outros."],
    [113, "Me sinto mais seguro seguindo o conselho das pessoas."],
    [114, "Sei que, na maioria das vezes, decepciono as pessoas."],
    [115, "Percebo que muitas vezes estou sentindo culpa."],
    [116, "A intimidade me incomoda."],
    [117, "Não falo da minha vida para ninguém."],
    [118, "Dificilmente permito que alguém tenha intimidade comigo."],
    [119, "Não dou espaço para \"intimidades\" e perguntas sobre minha vida."],
    [120, "Prefiro não conversar com as pessoas."],
    [121, "Não entendo porque as pessoas gostam tanto de fazer amizades."],
    [122, "Tenho pouco interesse em ter qualquer tipo de contato com as pessoas."],
    [123, "Somente me aproximo de alguém se eu não tiver escolha."],
    [124, "Dificilmente fico empolgado com alguma coisa."],
    [125, "É difícil, para mim, lembrar quando me emocionei."],
    [126, "Não entendo como as pessoas ficam tão empolgadas com as coisas."],
    [127, "É difícil eu ficar entusiasmado com algo."],
    [128, "Sinto-me extremamente mal quando preciso participar de atividades em grupo."],
    [129, "Sei que sou muito ansioso."],
    [130, "Na maior parte do tempo estou tenso."],
    [131, "As pessoas acham que sou uma pessoa muito preocupada com tudo."],
    [132, "Estou sempre preocupado com as coisas ruins que podem acontecer."],
    [133, "Somente converso com pessoas que não conheço se não houver outro jeito."],
    [134, "Para mim é muito difícil fazer amizade com alguém."],
    [135, "Não sei como me comportar na frente das pessoas."],
    [136, "Prefiro evitar relacionamentos amorosos."],
    [137, "Quando percebo que estou entrando em um relacionamento íntimo, termino o mais rápido possível."],
    [138, "Prefiro ficar sozinho, sem ter um parceiro amoroso."],
    [139, "Prefiro não me envolver emocionalmente com alguém."],
    [140, "Não há nada pior do que ser criticado pelas pessoas."],
    [141, "Frequentemente me sinto deslocado em diferentes situações."],
    [142, "Sei que as pessoas acham que não façam nada direito."],
    [143, "Somente vou a eventos sociais se eu realmente não conseguir evitar."],
    [144, "Tenho que ser agressivo com algumas pessoas, senão elas nunca aprenderão."],
    [145, "Não vejo problema em ofender alguém se for necessário."],
    [146, "Fico facilmente com raiva em diferentes situações."],
    [147, "Algumas pessoas me irritam muito."],
    [148, "Quando posso retribuo o mal que me fizeram."],
    [149, "As pessoas que já me prejudicaram precisam pagar por isso."],
    [150, "Sei ser maldoso quando necessário."],
    [151, "Evito ter amigos íntimos, pois eles poderão me trair a qualquer momento."],
    [152, "Às vezes investigo meus amigos ou parentes para descobrir o que estão tramando contra mim."],
    [153, "É necessário sempre testar as pessoas para verificar se elas não estão me prejudicando."],
    [154, "Não confio em ninguém para dar opinião sobre a minha vida."],
    [155, "Sempre prefiro não depender das pessoas para nada."],
    [156, "É importante que as coisas saiam do meu jeito em qualquer situação."],
    [157, "Gosto de estar no controle quando me relaciono com as pessoas."],
    [158, "Sei que existem pessoas por aí me espionando."],
    [159, "As pessoas deveriam sempre me ouvir, assim as coisas seriam melhores."],
    [160, "Muitas pessoas me consideram rabugento."],
    [161, "As pessoas me acham irritado, mas me irrito porque elas merecem."],
    [162, "As pessoas costumam me irritar com facilidade."],
    [163, "As coisas terríveis que podem acontecer me preocupam muito."],
    [164, "Serei prejudicado no futuro por erros que cometi no passado."],
    [165, "Pensar no futuro me deixa nervoso."],
    [166, "Sempre fui muito ansioso."],
    [167, "Sei que não há nada que eu possa fazer para melhorar meu futuro."],
    [168, "A vida das pessoas seria melhor se eu não estivesse aqui."],
    [169, "Às vezes penso que o suicídio seja a melhor opção para mim."],
    [170, "Uma das piores coisas que podem acontecer comigo é ficar sozinho na vida."],
    [171, "É horrível não ter as pessoas das quais gostamos sempre ao nosso lado."],
    [172, "Sou capaz até mesmo de me ferir quando perco o controle."],
    [173, "Geralmente as minhas ideias se sobressaem."],
    [174, "Muitos querem ser como eu."],
    [175, "Eu deveria ser recompensado pelo modo excelente com que faço as coisas."],
    [176, "Dificilmente encontro pessoas que conseguem fazer as coisas tão bem quanto eu."],
    [177, "Sei que as pessoas se incomodam ao perceberem que sou melhor que elas."],
    [178, "Preciso tomar cuidado com as pessoas que tem inveja de mim."],
    [179, "Os objetivos das pessoas não me interessam."],
    [180, "Me falta paciência para ouvir os problemas das pessoas."],
    [181, "É difícil me sensibilizar com o sofrimento alheio."],
    [182, "Não tenho tempo para ficar pensando em como os outros se sentem."],
    [183, "As pessoas acreditam facilmente no que falo."],
    [184, "Todos sempre acabam fazendo o que quero."],
    [185, "Sempre consigo o que quero."],
    [186, "Às vezes percebo que as coisas ao meu redor parecem irreais."],
    [187, "Frequentemente tenho a sensação de ser outra pessoa."],
    [188, "Muitas vezes fico \"fora do ar\" e quando volto muito tempo já se passou."],
    [189, "Tenho a impressão que as pessoas estão tramando contra mim."],
    [190, "Consigo, mesmo que por sinais ocultos, perceber quando alguém quer me prejudicar."],
    [191, "Acredito em poderes de outro mundo e muitas vezes estou conectado a eles."],
    [192, "Não entendo porque as pessoas se emocionam com tanta facilidade."],
    [193, "Já me falaram que não expresso meus sentimentos."],
    [194, "Muitas vezes faço coisas e não penso no que pode acontecer."],
    [195, "Não perco tempo avaliando as informações antes de tomar decisões."],
    [196, "Sei que sou impulsivo e não me importo com isso."],
    [197, "É inevitável que se tome decisões precipitadas muitas vezes."],
    [198, "Algumas pessoas me consideram irresponsável."],
    [199, "Correr riscos é um prazer para mim."],
    [200, "Uma vida sem riscos é muito sem graça."],
    [201, "Quando faço alguma aventura, não me importo se me machucar."],
    [202, "As pessoas consideram muitas coisas que faço como arriscadas."],
    [203, "Faço coisas perigosas sem pensar em limites."],
    [204, "Sempre faço o que quero, mesmo que seja muito perigoso."],
    [205, "Se for para o meu bem, posso usar as pessoas."],
    [206, "Considero importante ter o domínio das pessoas mais próximas a mim."],
    [207, "Posso fingir submissão se isso me levar a conseguir o que quero."],
    [208, "Para ter o que quero, vale a pena contar mentiras."],
    [209, "Tenho facilidade em adaptar as verdades a meu favor."],
    [210, "Minto sem remorso."]
  ];

  const questions = rawQuestions.map(([number, text], index) => {
    if (number !== index + 1) {
      throw new Error("Sequência inválida no item " + number + ".");
    }

    return {
      id: "item_" + number,
      number,
      text
    };
  });

  const data = {
    formCode: "IDCP2_V2",
    formName: "IDCP-2 - Inventário Dimensional Clínico da Personalidade",
    title: "Inventário Dimensional Clínico da Personalidade",
    shortTitle: "IDCP-2",
    prompt: "Leia cada afirmação e indique o quanto ela se aplica a você.",
    questions,
    responses: [
      { value: "nada", label: "Nada", score: 1 },
      { value: "pouco", label: "Pouco", score: 2 },
      { value: "moderadamente", label: "Moderadamente", score: 3 },
      { value: "muito", label: "Muito", score: 4 }
    ],
    itemsPerPage: 20
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = data;
  }

  if (globalScope) {
    globalScope.IDCP2Data = data;
  }
})(typeof window !== "undefined" ? window : globalThis);
